### ISSUE TITLE
Environment

### ISSUE THREAD

**Issue by willirath** [mardatade/Course-Visualization-with-Python#2]
Currently, there's both an `environment.yml` and a `requirements.txt`. I'm not sure how binder / repo2docker will prioritise the two, but I suggest going  for the `environment.yml` with a section:
```yaml
  - pip:
    - whatever
    - needed
    - from
    - pypi
```

This might also fix the bokeh saving errors.

**Comment by gitPrinz** [comment]
I would remove the `environment.yml`, since the `requirements.txt` are more helpful for me (pip install).
At first I thought both was needed.

If you agree, you can close this.

**Comment by willirath** [comment]
Sounds good to me. Just try dropping the `environment.yml` in a branch and make sure it works in binder.
